theme: jekyll-theme-slate
title: Estevao Alvarenga
description: [linkedin.com/in/efs-alvarenga](https://www.linkedin.com/in/efs-alvarenga/)
description: Operational Research Petroleum Engineer (CEng)
